# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 18:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(to='notecards.Tag'),
        ),
    ]
