# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-13 22:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0002_auto_20161213_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deck',
            name='tags',
            field=models.ManyToManyField(blank=True, to='notecards.Tag'),
        ),
    ]
