# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-05 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0004_auto_20170105_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='description',
            field=models.TextField(blank=True, default='', max_length=800),
        ),
    ]
