# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-06 00:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0005_deck_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='modified_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
