# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-30 19:29
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notecards', '0006_deck_modified_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiz_completed', models.BooleanField()),
                ('quiz_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('quiz_duration', models.PositiveIntegerField(default=0)),
                ('questions_attempted', models.PositiveIntegerField(default=0)),
                ('questions_correct', models.PositiveIntegerField(default=0)),
                ('deck', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='notecards.Deck')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
