# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0010_message_message_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_is_new',
            field=models.BooleanField(default=True),
        ),
    ]
