# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-07 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notecards', '0011_message_message_is_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatar',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, default="This user hasn't edited their bio yet!", max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='saved_decks',
            field=models.ManyToManyField(blank=True, to='notecards.Deck'),
        ),
    ]
