# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notecards', '0012_auto_20170307_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='deck',
            name='deck_hits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deck',
            name='deck_likes',
            field=models.ManyToManyField(blank=True, related_name='likers', to=settings.AUTH_USER_MODEL),
        ),
    ]
